enum DECK {
  VIEW_DECK = 'VIEW_DECK',
  ADD_CARD = 'ADD_CARD',
  REMOVE_CARD = 'REMOVE_CARD',
  CHANGE_NAME = 'CHANGE_NAME',
}

enum CARD {
  VIEW_CARD = 'VIEW_CARD'
}

enum ALERT {
  SET_SHOWING = 'SET_SHOWING',
  SET_CONTENT = 'SET_CONTENT',
  SET_SEVERITY = 'SET_SEVERITY'
}

export {
  DECK,
  CARD,
  ALERT
};