import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.scss';
import { useState } from 'react';

// Redux
import { useSelector, useDispatch } from 'react-redux';
import counterActions from '../store/actions/counterActions';
import { RootState } from '../store/reducers/rootReducer';


const Home = () => {
  const dispatch = useDispatch();
  const count = useSelector((state: RootState) => state.counterReducer.counter);

  const increment = () => {
    dispatch(counterActions.increment());
  };

  const decrement = () => {
    dispatch(counterActions.decrement());
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p>hi there</p>
      <p>{count}</p>
      <button onClick={increment}>increment</button>
      <button onClick={decrement}>decrement</button>
    </>
  )
}

export default Home;